### ISSUE TITLE
Builds still failing - '../Fabric/Fabric+FABKits.h' file not found

### ISSUE THREAD

**Issue by gabaum10** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#167]
So I am in the process of trying to switch off of phonegap build to a local cordova setup in hopes of getting deep links working in iOS.  Unfortunately, I still can't get the app to build with the latest version of the branch cordova plugin.  The error on the latest checked out from master (I have pretty much given up on using npm at this point) is still throwing an error: "'../Fabric/Fabric+FABKits.h' file not found".  Any idea what's going on here?  I thought this was fixed.  Before this, I had the plugin locked into version 2.0.9 on npm and that still worked, I just wasn't sure if it had everything to get the universal links working.  They didn't seem to be with my tests so I figured I'd get the latest off git and see if I had any more luck that way.

**Comment by gabaum10** [comment]
I guess what version started supporting the new link formats with the xxxx.app.link?  I'll just set it to that version and see if I can get the deep links working.

**Comment by aaustin** [comment]
I had resolved that issue on NPM with the latest version: 2.1.7. The problem was that NPM was collapsing all of the source files to 1 directly, making `./Fabric/Fabric+FABKits.h` an invalid directory reference.

Which version were you trying that caused it to break?

**Comment by gabaum10** [comment]
So I'm installing it via npm.  I used to have to fixed at 2.0.9 which was working, but I  was afraid it didn't support the new link convetions with the xxxx.app.link schemes.  So I tried to completely remove the project and re-build it adding the plugin like so: `cordova plugin add branch-cordova-sdk --variable BRANCH_KEY=branchKey --variable URI_SCHEME=uriScheme`.  After I updated to latest, I'm still seeing that Fabric.h error.  So I guess the npm fix didn't get rolled out or something?

**Comment by gabaum10** [comment]
The same error occurs when I install the plugin directly from git, so it doesn't look like a npm issue, cutting the uncertainty of installing from npm out of the equation like so: `cordova plugin add https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking.git --variable BRANCH_KEY=branchKey --variable URI_SCHEME=uriScheme`

**Comment by gabaum10** [comment]
Sorry, disregard that previous comment.  I hadn't updated the code on my build machine to use the git repo.  Now I did and the iOS builds are passing.  That said, I'll leave this ticket open to address the npm issue which still stands.  I'll just continue building off git.

**Comment by gabaum10** [comment]
Well the good news, after switching to using the master out of git, everything builds perfectly and I was FINALLY able to get universal links working in iOS.

**Comment by renesansz** [comment]
cool, good to hear that this issue is now resolved.
Will close the issue now. Thanks @gabaum10

**Comment by gabaum10** [comment]
Well, the npm issue is not resolved, which is why I left this open.  You guys probably want to try and fix that for future npm use.  Building out of git works fine though.
