### ISSUE TITLE
iOS App crashes after Resume from ScreenLock

### ISSUE THREAD

**Issue by malua** [BranchMetrics/cordova-ionic-phonegap-branch-deep-linking#202]
When I lock the screen with the running app in foreground and then unlock again, the app crashes after 2 to 3 seconds. (this is not happening on android)
Its definitly branch, as it works if i remove the <plugin> from the config.xml. do you have any idea what that could be? 
What should happen if Branch.initSession() is called twice? Could that be the problem?

this is the log from safari: i doesn't say very much to me, also because you can see no code hints or anything else. but maybe you can extract some information from that.
[crash log.txt](https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/files/447863/crash.log.txt)

thanks for your support!

**Comment by malua** [comment]
Updated to phonegap version 6.3.0. its not happening any more.

**Comment by malua** [comment]
Sorry for reopening this, but the error didn't go away by updating to phonegap 6.3.0. i have figured out, that the error appears when Branch.setIdentity() is called onResume. I think apple changed something with fore and background services. could that be causing this?

**Comment by malua** [comment]
Now I can't even build it anymore:

> "plugman install --platform ios --project /project --plugin branch-cordova-sdk@2.1.10 --var BRANCH_KEY=key_test_emc5NZRCzcw6E5NOB4thrhkfxFkORVk1 --var URI_SCHEME=ticketgretchen": Fetching plugin "branch-cordova-sdk@2.1.10" via npm
Installing "io.branch.sdk" at "2.1.10" for ios
Fetching plugin "https://github.com/vstirbu/PromisesPlugin.git" via git clone
Using shallow clone
Repository "https://github.com/vstirbu/PromisesPlugin.git" checked out to git ref "master" at "fdedfbc".
Installing "es6-promise-plugin" at "3.0.2" for ios
Checking dependencies:
Failed to install 'io.branch.sdk':Error: Cannot find module '/private/plugins/io.branch.sdk/package.json'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at readDependenciesFromPackageJson (/private/project/cordova/plugins/io.branch.sdk/hooks/beforePluginInstallHook.js:126:14)
    at module.exports (/private/project/cordova/plugins/io.branch.sdk/hooks/beforePluginInstallHook.js:150:17)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/hooks/HooksRunner.js:187:18)
    at runScript (/usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/hooks/HooksRunner.js:165:16)
    at /usr/local/lib/node_modules/pgb-plugman/node_modules/pgb-cordova-lib/src/hooks/HooksRunner.js:133:20
    at _fulfilled (/usr/local/lib/node_modules/pgb-plugman/node_modules/q/q.js:787:54)
Cannot find module '/private/plugins/io.branch.sdk/package.json'


Version 2.1.10 was just for testing. if i omit the version="2.1.10" tag, the same thing happens with 2.1.16 which is the newest i believe. fetching from git does not change anything either.

any help is much appreciated.

**Comment by malua** [comment]
Some more information: As I said, if .setIdentity is uncommented, it does not crash. Although if call Branch.setIdentity(2222222), the identity is set correctly (as seen in dashboard), but if the app is reactivated from background then, it crashes.

**Comment by aaustin** [comment]
Thanks for the extra info on this @malua. I'll have @renesansz take a look soon.

**Comment by renesansz** [comment]
thanks for the info @malua, will look into this.

**Comment by renesansz** [comment]
@malua , may I know what iOS version are you using? I've tested it on an actual device (iOS 9.3.5) and somehow the testbed app didn't crash.
I've tried doing the ff:
1. Initialize Branch
2. Set identity
3. Lock phone/Minimize testbed app
4. Unlock phone and open Branch/re-open testbed app
But I wasn't able to reproduce the issue that you're making

Also, can you provide some sample codes?

Thanks

**Comment by malua** [comment]
I have tested it on iOS 9.3.5 and 7.1.2. It's happening on both.
The testbed app is not a phonegap app, right? maybe it has to do with PhoneGap Build?

I am also not sure about the hooks working on PGB. could it be the PGB ignores a hook, and this happens therefor? but it compiles fine, and all the features are working. As for the code samples. I just call `Branch.initSession()` in `onDeviceReady` and 
```
function onResume(){
	setTimeout(function() {
	      Branch.initSession().then(function (res) {
		     console.log("initSession:");
	         console.log(res);
	    }).catch(function (err) {
	    	console.log("ERROR initSession:");
	        console.error(err);
	    });
    }, 0);
}
```
I added the timeout due to this : [Cordova Docs Resume Event](http://cordova.apache.org/docs/en/6.x/cordova/events/events.html#resume)

and then I set the identity when loading a profile like this:
```
if(model && model.id){
		Branch.setIdentity(model.id).then(function (res) {
			  // Success Callback
			console.log("setIdentity:");
			console.log(res);
		}).catch(function (err) {
			  // Error Callback
			console.log("ERROR setIdentity:");
			console.error(err);
		});;
}
```

If I uncomment the part about Branch.setIdentity() the app never crashes. and as i said if i call it manually from the debugging console in safari, the identity is set, but the app crashes after the next screenlock or if it was in the background.

**Comment by malua** [comment]
Oh no, I am getting a really bad feeling:
[https://github.com/phonegap/build/issues/279#issuecomment-200986755](https://github.com/phonegap/build/issues/279#issuecomment-200986755)

Maybe it's not possible to use Branch with PhoneGap Build at the moment?

**Comment by aaustin** [comment]
Hmm - thanks for linking to that PG error. I was unaware people were struggling with the entitlements that much. However, that's a very different error than the one you're describing and I'll address that in a separate issue I just created. I know this because at no point does the library read from the entitlements file. https://github.com/BranchMetrics/cordova-ionic-phonegap-branch-deep-linking/issues/207

Taking a look at your issue now.

**Comment by aaustin** [comment]
I'm pretty sure this is related to an issue (https://github.com/BranchMetrics/ios-branch-deep-linking/issues/424) on iOS that we just discovered, where it was possible for setIdentity to be executed before init was finished https://github.com/BranchMetrics/ios-branch-deep-linking/pull/428. I bet this causes some crash on Cordova.

We'll get this merged in ASAP.

**Comment by malua** [comment]
Is this merged already? I tried to add the plugin via git. and specified the branch update-ios-lib. unfortunately it is still crashing.

i moved our build process to local cli on osx. now i get better crash logs and now you can see its directly got to do with the setUserIdentity:

```
2016-09-15 13:07:53.238 Ticket Gretchen Wien[10667:455763] -[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x7b15edc0
2016-09-15 13:07:53.517 Ticket Gretchen Wien[10667:455763] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFNumber isEqualToString:]: unrecognized selector sent to instance 0x7b15edc0'
*** First throw call stack:
(
	0   CoreFoundation                      0x02c4d494 __exceptionPreprocess + 180
	1   libobjc.A.dylib                     0x026e0e02 objc_exception_throw + 50
	2   CoreFoundation                      0x02c57253 -[NSObject(NSObject) doesNotRecognizeSelector:] + 275
	3   CoreFoundation                      0x02b8c89d ___forwarding___ + 1037
	4   CoreFoundation                      0x02b8c46e _CF_forwarding_prep_0 + 14
	5   Ticket Gretchen Wien                0x002f4301 -[BNCPreferenceHelper setUserIdentity:] + 58
	6   Ticket Gretchen Wien                0x002f9e7f -[BranchOpenRequest processResponse:error:] + 538
	7   Ticket Gretchen Wien                0x002e9425 __30-[Branch processNextQueueItem]_block_invoke + 170
	8   Ticket Gretchen Wien                0x002f7ce4 __79-[BNCServerInterface genericHTTPRequest:retryNumber:log:callback:retryHandler:]_block_invoke.82 + 29
	9   libdispatch.dylib                   0x03c6a363 _dispatch_call_block_and_release + 15
	10  libdispatch.dylib                   0x03c8d9cd _dispatch_client_callout + 14
	11  libdispatch.dylib                   0x03c72f7c _dispatch_main_queue_callback_4CF + 910
	12  CoreFoundation                      0x02b971be __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 14
	13  CoreFoundation                      0x02b55434 __CFRunLoopRun + 2356
	14  CoreFoundation                      0x02b54846 CFRunLoopRunSpecific + 470
	15  CoreFoundation                      0x02b5465b CFRunLoopRunInMode + 123
	16  GraphicsServices                    0x04965664 GSEventRunModal + 192
	17  GraphicsServices                    0x049654a1 GSEventRun + 104
	18  UIKit                               0x0073aeb9 UIApplicationMain + 160
	19  Ticket Gretchen Wien                0x000d8d09 main + 89
	20  libdyld.dylib                       0x03cb7a25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)
```

**Comment by aaustin** [comment]
Hey @malua - I've merged it in this morning as part of the 2.2.0 update. Please update and let me know if you still observe the issue. Thanks!

**Comment by malua** [comment]
The update did not fix the issue, because the problem was a different one. I was calling .setIdentity with a integer, not a string. this works on android, but let's the app crash on ios due to this [__NSCFNumber isEqualToString:] in the branch ios sdk. maybe you can change that or make it more visible, that setIdentity can only be called with String. Thank you!
